/*
 * SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Adapted from https://github.com/vllm-project/vllm/blob/v0.14.0/csrc/moe/marlin_moe_wna16/
 * SPDX-License-Identifier: Apache-2.0
 * SPDX-FileCopyrightText: Copyright contributors to the vLLM project
 */
// auto generated by generate_kernels.py
// clang-format off

#include <cuda_runtime.h>

#include "kernel.h"
#include "marlin_template.h"

namespace MARLIN_NAMESPACE_NAME {


template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 256, 1, 8, 8, true, 4, -1, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 128, 1, 8, 4, true, 4, -1, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 256, 1, 8, 8, false, 4, -1, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 128, 1, 8, 4, false, 4, -1, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 256, 2, 16, 4, false, 4, -1, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 128, 2, 8, 4, false, 4, -1, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 256, 3, 16, 4, false, 4, -1, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 128, 3, 8, 4, false, 4, -1, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 256, 4, 16, 4, false, 4, -1, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 128, 4, 8, 4, false, 4, -1, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 256, 1, 8, 8, true, 4, 2, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 128, 1, 8, 4, true, 4, 2, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 256, 1, 8, 8, false, 4, 2, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 128, 1, 8, 4, false, 4, 2, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 256, 2, 16, 4, false, 4, 2, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 128, 2, 8, 4, false, 4, 2, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 256, 3, 16, 4, false, 4, 2, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 128, 3, 8, 4, false, 4, 2, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 256, 4, 16, 4, false, 4, 2, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 128, 4, 8, 4, false, 4, 2, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 256, 1, 8, 8, true, 4, 4, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 128, 1, 8, 4, true, 4, 4, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 256, 1, 8, 8, false, 4, 4, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 128, 1, 8, 4, false, 4, 4, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 256, 2, 16, 4, false, 4, 4, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 128, 2, 8, 4, false, 4, 4, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 256, 3, 16, 4, false, 4, 4, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 128, 3, 8, 4, false, 4, 4, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 256, 4, 16, 4, false, 4, 4, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 128, 4, 8, 4, false, 4, 4, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 256, 1, 8, 8, true, 4, 8, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 128, 1, 8, 4, true, 4, 8, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 256, 1, 8, 8, false, 4, 8, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 128, 1, 8, 4, false, 4, 8, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 256, 2, 16, 4, false, 4, 8, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 128, 2, 8, 4, false, 4, 8, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 256, 3, 16, 4, false, 4, 8, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 128, 3, 8, 4, false, 4, 8, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 256, 4, 16, 4, false, 4, 8, false>( MARLIN_KERNEL_PARAMS );

template __global__ void Marlin<trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kU4.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), trt_edgellm::marlin_dtypes::kFloat16.id(), 128, 4, 8, 4, false, 4, 8, false>( MARLIN_KERNEL_PARAMS );

}
